export PATH=~/bin:/opt/local/bin:/usr/local/mysql/bin:/usr/texbin:/usr/local/bin:$HOME/.rvm/bin:/usr/local/heroku/bin:$PATH
export PATH=/usr/local/bin:$HOME/.gems/bin:$HOME/bin:$PATH
export EDITOR="code --wait"

alias settitle='printf "\033]0;%s\007"'
alias git="hub"
alias g="git"

# git aliases
## delete merged branches:
alias git-scrub='git branch --merged | grep -v "master" | grep -v "main" | xargs git branch -d'
## delete all branches but master:
alias git-clean='git branch | grep -v "master" | grep -v "main" | xargs git branch -D'
